import Arguments
import Concatenation
import Foundation

enum ConcatAnyCommand: ArgumentCommand {
    static let name = "any"

    static var defaultChild: ConcatAnyRunCommand.Type {
        ConcatAnyRunCommand.self
    }

    static var children: [ArgumentCommandType] {
        [
            ConcatAnyInitCommand.self,
            ConcatAnyRunCommand.self,
        ]
    }

    static func components() throws -> [CommandComponentLowerable] {
        [
            about("Concatenate arbitrary absolute/relative files via .conany."),
        ]
    }
}

enum ConcatAnyInitCommand: RunnableArgumentCommand {
    static let name = "init"

    static func components() throws -> [CommandComponentLowerable] {
        [
            flag(
                "force",
                help: "Force overwrite existing .conany."
            ),
        ]
    }

    static func run(
        _ invocation: ParsedInvocation
    ) async throws {
        let initializer = ConAnyInitializer()

        do {
            try initializer.initialize(
                force: try invocation.flag("force")
            )
            print(".conany created.")
        } catch ConAnyInitError.alreadyExists {
            print(".conany already exists. Use --force to overwrite.")
        }
    }
}

enum ConcatAnyRunCommand: RunnableArgumentCommand {
    static let name = "run"

    static func components() throws -> [CommandComponentLowerable] {
        [
            opt(
                "config",
                as: String.self,
                help: "Path to .conany."
            ),
            flag(
                "verbose",
                help: "Verbose resolution."
            ),
        ] + ConcatOptions.components()
    }

    static func run(
        _ invocation: ParsedInvocation
    ) async throws {
        let options = try ConcatOptions.parse(
            invocation
        )

        try runConAny(
            configPath: try invocation.value(
                "config",
                as: String.self
            ),
            options: options,
            verbose: try invocation.flag(
                "verbose"
            )
        )
    }
}

func runConAny(
    configPath: String?,
    options: ConcatOptions,
    verbose: Bool
) throws {
    let cwd = FileManager.default.currentDirectoryPath
    let cfgURL = URL(
        fileURLWithPath: configPath ?? "\(cwd)/.conany"
    ).standardizedFileURL

    let cfg = try ConAnyParser.parseFile(
        at: cfgURL
    )

    let finalMap: IgnoreMap
    if let parsed = try? ConignoreParser.parseFile(
        at: URL(fileURLWithPath: cwd + "/.conignore")
    ) {
        finalMap = try IgnoreMap(
            ignoreFiles: parsed.ignoreFiles + options.excludeFiles,
            ignoreDirectories: parsed.ignoreDirectories + options.excludeDirs,
            obscureValues: parsed.obscureValues
        )
    } else {
        finalMap = try IgnoreMap(
            ignoreFiles: options.excludeFiles,
            ignoreDirectories: options.excludeDirs,
            obscureValues: [:]
        )
    }

    let resolver = ConAnyResolver(
        baseDir: cfgURL.deletingLastPathComponent().path
    )

    var collectedContexts: [String] = []

    let containsContexts = cfg.renderables.contains {
        $0.context != nil
    }

    if containsContexts {
        let signature = """
        // type: autogenerated
        // signature: concatenator
        """

        collectedContexts.append(signature)
    }

    var totalLinesAll = 0

    for renderable in cfg.renderables {
        let matches = try resolver.resolveMatches(
            renderable,
            maxDepth: options.allSubdirectories ? nil : options.depth,
            includeDotfiles: options.includeDotFiles,
            ignoreMap: finalMap,
            verbose: verbose
        )

        let urls = matches.map(\.url)

        let selectedContentByFile = Dictionary(
            uniqueKeysWithValues: matches.map {
                (
                    $0.url.standardizedFileURL,
                    $0.contentSelections
                )
            }
        )

        let presentedPathByFile = Dictionary(
            uniqueKeysWithValues: matches.map { match in
                (
                    match.url.standardizedFileURL,
                    resolver.presentedPath(
                        for: match.url,
                        in: renderable
                    )
                )
            }
        )

        guard !urls.isEmpty else {
            print("No files matched block → \(renderable.output)")
            continue
        }

        let outURL = resolver.outputURL(
            for: renderable
        )

        let location = "con any block '\(renderable.output)' → \(outURL.path)"

        if let context = renderable.context {
            let header = context.object(
                outputURL: outURL
            )
            collectedContexts.append(header)
        }

        let concatenator = FileConcatenator(
            inputFiles: urls,
            outputURL: outURL,
            context: renderable.context,
            selectedContentByFile: selectedContentByFile,
            presentedPathByFile: presentedPathByFile,

            delimiterStyle: options.delimiterStyle,
            delimiterClosure: options.delimiterClosure,
            maxLinesPerFile: options.limit(),
            trimBlankLines: true,
            relativePaths: false,
            rawOutput: options.rawOutput,
            outputFormat: options.outputFormat,
            includeSourceLineNumbers: options.includeSourceLineNumbers,
            includeSourceModifiedAt: options.includeSourceModifiedAt,
            obscureMap: finalMap.obscureValues,

            copyToClipboard: options.copyToClipboard,
            verbose: options.verboseOutput,

            location: location,
            allowSecrets: options.allowSecrets,
            deepSecretInspection: options.deepInspect
        )

        let total = try concatenator.run()
        totalLinesAll += total

        printSuccess(
            outputPath: outURL.path,
            totalLines: total
        )
    }

    try writeContextIndexIfNeeded(
        collectedContexts: collectedContexts,
        configURL: cfgURL,
        verbose: verbose
    )

    if cfg.renderables.count > 1 {
        print("Done. Blocks: \(cfg.renderables.count), total lines: \(totalLinesAll).")
    }
}

private func writeContextIndexIfNeeded(
    collectedContexts: [String],
    configURL: URL,
    verbose: Bool
) throws {
    guard !collectedContexts.isEmpty else {
        return
    }

    let contextsJoined = collectedContexts.joined(
        separator: "\n\n"
    )

    let contextsURL = configURL
        .deletingLastPathComponent()
        .appendingPathComponent("context_index.txt")

    if FileManager.default.fileExists(
        atPath: contextsURL.path
    ) {
        let text = try String(
            contentsOf: contextsURL,
            encoding: .utf8
        )

        if isConcatenatorSigned(
            text: text
        ) {
            try contextsJoined.write(
                to: contextsURL,
                atomically: true,
                encoding: .utf8
            )

            if verbose {
                print("Overwrote autogenerated contexts at \(contextsURL.path)")
            }
        } else if verbose {
            print("Skipping contexts write: \(contextsURL.path) exists and appears manually maintained.")
        }
    } else {
        try contextsJoined.write(
            to: contextsURL,
            atomically: true,
            encoding: .utf8
        )

        if verbose {
            print("Wrote contexts to \(contextsURL.path)")
        }
    }
}

private func isConcatenatorSigned(
    text: String
) -> Bool {
    let firstLines = text
        .split(separator: "\n", omittingEmptySubsequences: false)
        .prefix(10)
        .map(String.init)

    let hasTypeMarker = firstLines.contains {
        $0.trimmingCharacters(
            in: .whitespacesAndNewlines
        ) == "// type: autogenerated"
    }

    let hasSignature = firstLines.contains {
        $0.trimmingCharacters(
            in: .whitespacesAndNewlines
        ) == "// signature: concatenator"
    }

    return hasTypeMarker && hasSignature
}
