import Arguments
import Concatenation
import Foundation
import IO

enum ConcatAnyCommand: ArgumentCommand {
    static let name = "any"

    static var defaultChild: ConcatAnyRunCommand.Type {
        ConcatAnyRunCommand.self
    }

    static var children: [ArgumentCommandType] {
        [
            ConcatAnyInitCommand.self,
            ConcatAnyRunCommand.self,
        ]
    }

    static func components() throws -> [CommandComponentLowerable] {
        [
            about("Concatenate arbitrary absolute/relative files via .conany."),
        ]
    }
}

enum ConcatAnyInitCommand: RunnableArgumentCommand {
    static let name = "init"

    static func components() throws -> [CommandComponentLowerable] {
        [
            flag(
                "force",
                help: "Force overwrite existing .conany."
            ),
        ]
    }

    static func run(
        _ invocation: ParsedInvocation
    ) async throws {
        let initializer = ConAnyInitializer()

        do {
            try initializer.initialize(
                force: try invocation.flag("force")
            )
            print(".conany created.")
        } catch ConAnyInitError.alreadyExists {
            print(".conany already exists. Use --force to overwrite.")
        }
    }
}

enum ConcatAnyRunCommand: RunnableArgumentCommand {
    static let name = "run"

    static func components() throws -> [CommandComponentLowerable] {
        [
            opt(
                "config",
                as: String.self,
                help: "Path to .conany."
            ),
            flag(
                "verbose",
                help: "Verbose resolution."
            ),
        ] + ConcatOptions.components()
    }

    static func run(
        _ invocation: ParsedInvocation
    ) async throws {
        let options = try ConcatOptions.parse(
            invocation
        )

        try await runConAny(
            configPath: try invocation.value(
                "config",
                as: String.self
            ),
            options: options,
            verbose: try invocation.flag(
                "verbose"
            )
        )
    }
}

func runConAny(
    configPath: String?,
    options: ConcatOptions,
    verbose: Bool
) async throws {
    let cwd = FileManager.default.currentDirectoryPath
    let cfgURL = URL(
        fileURLWithPath: configPath ?? "\(cwd)/.conany"
    ).standardizedFileURL

    let cfg = try ConAnyParser.parseFile(
        at: cfgURL
    )

    let workspace = ConcatenationWorkspace(
        configuration: cfgURL
    )

    let finalMap: IgnoreMap
    if let parsed = try? ConignoreParser.parseFile(
        at: URL(fileURLWithPath: cwd + "/.conignore")
    ) {
        finalMap = try IgnoreMap(
            ignoreFiles: parsed.ignoreFiles + options.excludeFiles,
            ignoreDirectories: parsed.ignoreDirectories + options.excludeDirs,
            obscureValues: parsed.obscureValues
        )
    } else {
        finalMap = try IgnoreMap(
            ignoreFiles: options.excludeFiles,
            ignoreDirectories: options.excludeDirs,
            obscureValues: [:]
        )
    }

    let resolver = ConAnyResolver(
        baseDir: cfgURL.deletingLastPathComponent().path
    )

    var collectedContexts: [String] = []

    let containsContexts = cfg.renderables.contains {
        $0.context != nil
    }

    if containsContexts {
        let signature = """
        // type: autogenerated
        // signature: concatenator
        """

        collectedContexts.append(signature)
    }

    var totalLinesAll = 0
    var refreshContextIndex = false

    for renderable in cfg.renderables {
        let matches = try resolver.resolveMatches(
            renderable,
            maxDepth: options.allSubdirectories ? nil : options.depth,
            includeDotfiles: options.includeDotFiles,
            ignoreMap: finalMap,
            verbose: verbose
        )

        let urls = matches.map(\.url)

        let selectedContentByFile = Dictionary(
            uniqueKeysWithValues: matches.map {
                (
                    $0.url.standardizedFileURL,
                    $0.contentSelections
                )
            }
        )

        let presentedPathByFile = Dictionary(
            uniqueKeysWithValues: matches.map { match in
                (
                    match.url.standardizedFileURL,
                    resolver.presentedPath(
                        for: match.url,
                        in: renderable
                    )
                )
            }
        )

        guard !urls.isEmpty else {
            print("No files matched block → \(renderable.output)")
            continue
        }

        let outURL = resolver.outputURL(
            for: renderable
        )

        let location = "con any block '\(renderable.output)' → \(outURL.path)"

        if let context = renderable.context {
            let header = context.object(
                outputURL: outURL
            )
            collectedContexts.append(header)
        }

        let concatenator = FileConcatenator(
            inputFiles: urls,
            outputURL: outURL,
            context: renderable.context,
            workspace: workspace,
            selectedContentByFile: selectedContentByFile,
            presentedPathByFile: presentedPathByFile,

            delimiterStyle: options.delimiterStyle,
            delimiterClosure: options.delimiterClosure,
            maxLinesPerFile: options.limit(),
            trimBlankLines: true,
            relativePaths: false,
            rawOutput: options.rawOutput,
            outputFormat: options.outputFormat,
            includeSourceLineNumbers: options.includeSourceLineNumbers,
            includeSourceModifiedAt: options.includeSourceModifiedAt,
            obscureMap: finalMap.obscureValues,

            copyToClipboard: options.copyToClipboard,
            verbose: options.verboseOutput,

            location: location,
            allowSecrets: options.allowSecrets,
            deepSecretInspection: options.deepInspect
        )

        let result = try await concatenator.write(
            concurrency: .automatic
        )

        totalLinesAll += result.renderedLineCount

        if result.performedWrite {
            refreshContextIndex = true
        }

        printSuccess(
            outputPath: outURL.path,
            totalLines: result.renderedLineCount
        )
    }

    try writeContextIndexIfNeeded(
        collectedContexts: collectedContexts,
        configURL: cfgURL,
        refresh: refreshContextIndex,
        verbose: verbose
    )

    if cfg.renderables.count > 1 {
        print("Done. Blocks: \(cfg.renderables.count), total lines: \(totalLinesAll).")
    }
}

private func writeContextIndexIfNeeded(
    collectedContexts: [String],
    configURL: URL,
    refresh: Bool,
    verbose: Bool
) throws {
    let contextsURL = configURL
        .deletingLastPathComponent()
        .appendingPathComponent("context_index.txt")

    let exists = FileManager.default.fileExists(
        atPath: contextsURL.path
    )

    if collectedContexts.isEmpty {
        guard exists else {
            return
        }

        let text = try String(
            contentsOf: contextsURL,
            encoding: .utf8
        )

        guard isConcatenatorSigned(
            text: text
        ) else {
            return
        }

        try FileSystem.default.remove(
            contextsURL
        )

        if verbose {
            print(
                "Removed obsolete autogenerated contexts at \(contextsURL.path)"
            )
        }

        return
    }

    let contextsJoined = collectedContexts.joined(
        separator: "\n\n"
    )

    if exists {
        let text = try String(
            contentsOf: contextsURL,
            encoding: .utf8
        )

        guard isConcatenatorSigned(
            text: text
        ) else {
            if verbose {
                print(
                    "Skipping contexts write: \(contextsURL.path) exists and appears manually maintained."
                )
            }

            return
        }

        let materialChanged = contextIndexMaterial(
            text
        ) != contextIndexMaterial(
            contextsJoined
        )

        guard refresh || materialChanged else {
            if verbose {
                print(
                    "Unchanged autogenerated contexts at \(contextsURL.path)"
                )
            }

            return
        }

        try contextsJoined.write(
            to: contextsURL,
            atomically: true,
            encoding: .utf8
        )

        if verbose {
            print(
                "Overwrote autogenerated contexts at \(contextsURL.path)"
            )
        }

        return
    }

    try contextsJoined.write(
        to: contextsURL,
        atomically: true,
        encoding: .utf8
    )

    if verbose {
        print(
            "Wrote contexts to \(contextsURL.path)"
        )
    }
}

private func contextIndexMaterial(
    _ text: String
) -> String {
    text.replacingOccurrences(
        of: #""generated_at"\s*:\s*"[^"]*""#,
        with: #""generated_at" : "<generated_at>""#,
        options: .regularExpression
    )
}

private func isConcatenatorSigned(
    text: String
) -> Bool {
    let firstLines = text
        .split(separator: "\n", omittingEmptySubsequences: false)
        .prefix(10)
        .map(String.init)

    let hasTypeMarker = firstLines.contains {
        $0.trimmingCharacters(
            in: .whitespacesAndNewlines
        ) == "// type: autogenerated"
    }

    let hasSignature = firstLines.contains {
        $0.trimmingCharacters(
            in: .whitespacesAndNewlines
        ) == "// signature: concatenator"
    }

    return hasTypeMarker && hasSignature
}
